const {test}=require('node:test');const assert=require('node:assert/strict');
const {Session,stuck,helper}=require('../agent-teaching.js');
const view=()=>({schemaVersion:6,observationMode:'player-perception',contract:{},decision:'world',player:{x:0,y:0,health:2,maxHealth:2},inventory:[],room:{id:'a',entities:[],items:[],hitWarnings:[],tiles:[]}});
function setup(){let v=view();const written=[];const agent={async reset(){},perceive:()=>structuredClone(v),async step(a){v.player.x++;return {info:{recorded:true,turnDelta:1},terminated:false,truncated:false}},exportReplay:()=>({})};const store={async save(){},async append(id,r){written.push(r)}};const policy={name:'test',reset(){},choose:()=>({action:{type:'Move',direction:'right'}}),advance(){}};const session=new Session({agent,policy,store,meta:{id:'test',seed:1}});return {session,agent,store,policy,written};}
test('human input requires explicit takeover and records provenance',async()=>{const {session:s,written}=setup();await s.start('demonstration');assert.equal(await s.human({type:'Move',direction:'right'}),false);await s.take();await s.human({type:'Move',direction:'right'});assert.equal(written.length,1);assert.equal(written[0].source,'human');assert.equal(written[0].before.player.x,0);assert.equal(written[0].after.player.x,1);assert.equal(written[0].segment,1);});
test('takeover waits for executing action and does not duplicate input',async()=>{const {session:s,agent}=setup();await s.start('watch');let release;agent.step=()=>new Promise(r=>release=()=>r({info:{recorded:true,turnDelta:0},terminated:false,truncated:false}));const running=s.resume();await new Promise(r=>setImmediate(r));const take=s.take();assert.equal(s.state,'handoff');assert.equal(await s.human({type:'Move',direction:'up'}),false);release();await take;await running;assert.equal(s.state,'human');assert.equal(s.records.length,1);});
test('late policy response after pause never executes',async()=>{const {session:s,policy}=setup();let release;policy.choose=()=>new Promise(r=>release=r);await s.start('watch');const running=s.resume();await new Promise(r=>setImmediate(r));s.pause();release({action:{type:'Move',direction:'right'}});await running;assert.equal(s.records.length,0);assert.equal(s.state,'paused');});
test('failed local save retains exportable action and prevents continuation',async()=>{const {session:s,store}=setup();await s.start('demonstration');await s.take();store.append=async()=>{throw new Error('quota full')};await s.human({type:'Move',direction:'right'});assert.equal(s.state,'error');assert.equal((await s.export()).records.length,1);await s.resume();assert.equal(s.records.length,1);});
test('same-position attacks and food do not become blocked-move warnings',()=>{const v=view();const rows=Array.from({length:6},(_,i)=>({source:'agent',action:{type:'Move'},before:v,after:v,info:{recorded:true,turnDelta:0}}));assert.equal(stuck(rows),null);rows.forEach(r=>r.info.recorded=false);assert.match(stuck(rows),/no effect/);rows[2].source='human';assert.equal(stuck(rows),null);});
test('zero-turn food remains a helper decision and has no forced tick',()=>{const v=view();v.player.health=1;v.inventory=[{slot:0,healingAmount:1,useTurnCost:0}];assert.deepEqual(helper(v),{type:'UseItem',slotIndex:0});});
test('pause during takeover metadata save cannot enable human input afterward',async()=>{const {session:s,store}=setup();await s.start('watch');let release;store.save=()=>new Promise(r=>release=r);const taking=s.take();s.pause();release();await taking;assert.equal(s.state,'paused');assert.equal(await s.human({type:'Move',direction:'up'}),false);});
test('two sessions keep independent records and controller states',async()=>{const a=setup().session,b=setup().session;await Promise.all([a.start('watch'),b.start('demonstration')]);await a.resume(true);await b.take();await b.human({type:'Move',direction:'down'});assert.equal(a.state,'paused');assert.equal(b.state,'human');assert.equal(a.records[0].source,'agent');assert.equal(b.records[0].source,'human');assert.equal(a.records.length,1);});
test('shadow baseline predictions do not mutate policy memory',()=>{const {Baseline}=require('../agent-teaching.js');class Policy{constructor(){this.count=0;this.visits=new Map();}choose(){this.count++;this.visits.set('a',this.count);return {type:'Move',direction:'up'};}feedback(){this.count++;}}const p=new Baseline(Policy);p.reset();p.propose(view());p.propose(view());assert.equal(p.policy.count,0);assert.equal(p.policy.visits.size,0);p.choose(view());p.advance({source:'agent',before:view(),after:view(),action:{type:'Move',direction:'up'},info:{}});assert.equal(p.policy.count,2);});
test('doorway cycles request review but visible combat suppresses cycle warnings',()=>{const rows=Array.from({length:6},(_,i)=>{const after=view();after.room.id=i%2?'a':'b';return {source:'agent',action:{type:'Move'},before:view(),after,info:{recorded:true,turnDelta:1}};});assert.match(stuck(rows),/cycle/);rows[3].before.room.entities.push({isEnemy:true});assert.equal(stuck(rows),null);});
test('known solid walls are masked without hiding attacks, doors or unknown terrain',()=>{const {allowedDirections}=require('../agent-teaching.js');const v=view();v.inventory=[{activeWeapon:true,traits:{attackPattern:'adjacent-cardinal'}}];v.room.tiles=[{x:1,y:0,solid:true,kind:'Wall',isDoor:false}];assert.equal(allowedDirections(v).includes('right'),false);v.room.entities=[{x:1,y:0,width:1,height:1}];assert.equal(allowedDirections(v).includes('right'),true);v.room.entities=[];v.room.tiles[0].isDoor=true;assert.equal(allowedDirections(v).includes('right'),true);v.room.tiles[0].isDoor=false;v.room.tiles[0].solid=null;assert.equal(allowedDirections(v).includes('right'),true);});
test('recoverable menu rejection preserves the run and permits explicit takeover',async()=>{const {session:s,agent,written}=setup();await s.start('watch');agent.step=async()=>{throw Object.assign(new Error('Cannot use Move for current decision: ladder'),{code:'AGENT_ACTION_REJECTED'});};await s.resume(true);assert.equal(s.state,'help');assert.equal(written[0].source,'rejected');assert.equal(written[0].info.recorded,false);await s.take();assert.equal(s.state,'human');});
