'use strict';const test=require('node:test'),assert=require('node:assert/strict');
const R=process.env.HORIZON_REPO||require('node:path').resolve(__dirname,'../..');const W=require(R+'/agent-horizon-world.js');const {fixture,room}=require('./expedition-fixture.cjs');
function setup(options){const f=fixture(options),ledger=W.createLedger({episodeId:'test'}),director=W.createDirector({ledger,radius:3});const input=()=>({view:f.live.observe(),geometry:f.live.inspectHorizonIntent(),provenance:'live'});director.observe(input());return{...f,ledger,director,input};}
async function move(s,direction){const from=s.live.observe(),r=await s.live.advance({type:'Move',direction}),to=s.live.observe();s.director.observe({...s.input(),transition:{action:{type:'Move',direction},from:{roomId:from.room.id,...from.player},to:{roomId:to.room.id,...to.player},parity:true,recorded:r.info.recorded,healthLoss:0}});}
test('ledger refuses simulated provenance and leaves knowledge unchanged',()=>{const s=setup(),before=s.ledger.exportData();assert.throws(()=>s.ledger.observe({...s.input(),provenance:'simulation'}),/Hypothetical/);assert.deepEqual(s.ledger.exportData(),before);});
test('repeated real observation is idempotent, does not count a live action',()=>{const s=setup(),before=s.ledger.exportData();s.director.observe(s.input());assert.deepEqual(s.ledger.exportData(),before);});
test('new episode and rewind are not merged by equal room coordinates',async()=>{const s=setup();await move(s,'right');s.live.state.steps=0;assert.throws(()=>s.director.observe(s.input()),/Reset/);const q=s.input();q.view.contract.buildId='new';assert.throws(()=>s.director.observe(q),/changed/);});
test('known source episode metadata is explicit and bounded',()=>{assert.throws(()=>W.createLedger({}),/episodeId/);assert.throws(()=>W.createLedger({episodeId:'x',maxRooms:0}),/maxRooms/);});
test('capacity failure is atomic and does not evict old knowledge',()=>{const s=setup(),l=W.createLedger({episodeId:'tiny',maxTiles:1});assert.throws(()=>l.observe(s.input()),/capacity/);assert.equal(l.summary().roomCount,0);});
test('full room geometry is not mistaken for unseen floor requiring every tile visit',()=>{const s=setup({rooms:[room('A')]}),selected=s.director.select(s.input());assert.equal(selected,null);assert.equal(s.director.snapshot().diagnostic.reason,'NO_ACTIONABLE_KNOWN_OBJECTIVE');});
test('partial perception exposes a frontier, but a BFS cutoff is not exhaustion',()=>{const s=setup({rooms:[room('A')]}),q=s.input();q.geometry.coverage='partial';q.geometry.tiles=q.geometry.tiles.filter(t=>t.x<4);s.director.observe(q);const g=s.director.select(q);assert.equal(g.objective.motivation,'EXPLORE_REGION');const d=W.createDirector({ledger:s.ledger,maxExpanded:1});d.observe(q);d.select(q);assert.equal(d.snapshot().diagnostic.searchCutOff,true);});
test('local goal remains bounded while persistent passage target survives waypoints',async()=>{const s=setup();let p=s.director.select(s.input());const id=p.objective.id;assert.equal(p.goal.kind,'position');assert.equal(p.goal.x,4);await move(s,'right');p=s.director.select(s.input());assert.equal(p.objective.id,id);assert.equal(p.goal.x,5);});
test('new room chooses unexplored exit instead of immediately reversing arrival',async()=>{const s=setup();for(let i=0;i<5;i++)await move(s,'right');assert.equal(s.live.state.id,'B');const p=s.director.select(s.input());assert.equal(p.objective.motivation,'FOLLOW_NEW_PASSAGE');assert.equal(p.goal.x,4);assert.equal(s.ledger.summary().roomCount,2);});
test('directed passage records traversal only after verified live commit',async()=>{const s=setup();for(let i=0;i<5;i++)await move(s,'right');const edges=s.ledger.passages();const forward=edges.find(e=>e.from==='[0,"A"]');assert.equal(forward.to,'[0,"B"]');assert.equal(forward.traversals,1);const reverse=edges.find(e=>e.from==='[0,"B"]'&&e.x===0);assert.equal(reverse.to,'[0,"A"]');assert.equal(reverse.traversals,0);assert.equal(reverse.evidence,'observed-directed-link');});
test('empty dead end backtracks, cyclic completed graph does not force repeated route',async()=>{const s=setup();for(let i=0;i<10;i++)await move(s,'right');assert.equal(s.live.state.id,'C');let p=s.director.select(s.input());assert.equal(p.objective.motivation,'BACKTRACK');await move(s,'left');assert.equal(s.live.state.id,'B');p=s.director.select(s.input());assert.equal(p.objective.motivation,'BACKTRACK');for(let i=0;i<5;i++)await move(s,'left');assert.equal(s.live.state.id,'A');assert.equal(s.director.select(s.input()),null);});
test('unverified transitions and duplicate transition events do not change ledger',async()=>{const s=setup(),q=s.input(),before=s.ledger.exportData();assert.throws(()=>s.ledger.observe({...q,transition:{parity:false}}),/verified/);assert.deepEqual(s.ledger.exportData(),before);await move(s,'right');const next=s.ledger.exportData();assert.throws(()=>s.ledger.observe({...s.input(),transition:{parity:true,recorded:true,healthLoss:0,from:{roomId:'A',x:1,y:1,z:0},to:{roomId:'A',x:2,y:1,z:0}}}),/verified/);assert.deepEqual(s.ledger.exportData(),next);});
test('confirmed passage destination mutation fails before any write',async()=>{const s=setup();for(let i=0;i<5;i++)await move(s,'right');await move(s,'left');const q=s.input(),before=s.ledger.exportData();q.geometry.tiles.find(t=>t.x===6&&t.y===1).destination={roomId:'bogus',depth:0};assert.throws(()=>s.ledger.observe(q),/destination changed/);assert.deepEqual(s.ledger.exportData(),before);});
test('observed item disappears as absent, not falsely labelled collected',()=>{const s=setup({rooms:[room('A',{items:[{id:'heart',x:3,y:1,z:0,healingAmount:2}]})]});s.live.state.world.A.items=[];s.director.observe(s.input());assert.equal(s.ledger.room('[0,"A"]').opportunities[0].status,'absent');});
test('healing, boss progress, optional clearing and escape are distinct motives',()=>{const s=setup({rooms:[room('A',{items:[{id:'heart',x:2,y:1,z:0,healingAmount:2}],entities:[{id:'e',x:3,y:1,z:0,isEnemy:true,collidable:true,health:2}],boss:true})]});assert.equal(s.director.select(s.input()).objective.motivation,'BOSS_PROGRESS');s.live.state.health=3;s.director.observe(s.input());assert.equal(s.director.select(s.input()).objective.motivation,'COLLECT_RESOURCE');s.live.state.world.A.warnings=[{x:1,y:1,dangerous:true,hostile:true}];s.director.observe(s.input());assert.equal(s.director.select(s.input()).objective.motivation,'ESCAPE');});
test('ordinary room clearing is opt-in and still produces position goals only',()=>{const s=setup({rooms:[room('A',{entities:[{id:'e',x:3,y:1,z:0,isEnemy:true,collidable:true,health:2}]})]});assert.equal(s.director.select(s.input()),null);const d=W.createDirector({ledger:s.ledger,clearRooms:true});d.observe(s.input());assert.equal(d.select(s.input()).objective.motivation,'CLEAR_ROOM');});
test('failed objective is deferred not impossible; explicit retry releases it',()=>{const s=setup();s.director.select(s.input());s.director.feedback({type:'no-safe-prefix'});assert.equal(s.director.snapshot().deferred[0].status,'deferred-not-impossible');assert.equal(s.director.select(s.input()),null);s.director.retryDeferred();assert.ok(s.director.select(s.input()));});
test('material change invalidates the failed-state deferral',()=>{const s=setup();s.director.select(s.input());s.director.feedback({type:'no-safe-prefix'});s.live.state.world.A.items=[{id:'new',x:2,y:1,z:0}];s.director.observe(s.input());assert.ok(s.director.select(s.input()));});
test('Jev offers whitelist objective IDs and reject raw moves, stale and duplicate responses',async()=>{const s=setup();const offer=s.director.offer();assert.ok(offer.candidates.length);assert.ok(!offer.candidates[0].action);assert.equal(s.director.accept({token:offer.token,objectiveId:'Move:right'}),false);assert.equal(s.director.accept({token:offer.token,objectiveId:offer.candidates[0].id}),true);assert.equal(s.director.accept({token:offer.token,objectiveId:offer.candidates[0].id}),false);const next=s.director.offer();await move(s,'right');assert.equal(s.director.accept({token:next.token,objectiveId:next.candidates[0].id}),false);});
test('Jev preferred objective triggers reevaluation but does not execute a move',()=>{const s=setup();const selected=s.director.select(s.input()),offer=s.director.offer();assert.equal(s.director.accept({token:offer.token,objectiveId:offer.candidates[0].id}),true);assert.equal(s.director.select.shouldReselect({view:s.live.observe(),goal:selected.goal}),true);assert.equal(s.counts().live,0);});
test('ledger exports and room queries are detached, never expose mutable internals',()=>{const s=setup(),r=s.ledger.room('[0,"A"]');r.tiles.length=0;assert.equal(s.ledger.room('[0,"A"]').tiles.length,21);assert.ok(Object.isFrozen(s.ledger.exportData()));});
test('same coordinates on different floors are distinct world nodes',()=>{const s=setup();s.live.state.world.A.depth=1;s.director.observe(s.input());assert.equal(s.ledger.summary().roomCount,2);});
test('objectives never assume unknown or different object heights equal the player layer',()=>{const s=setup({rooms:[room('A',{items:[{id:'upper',x:2,y:1,z:1},{id:'unknown',x:3,y:1}]})]});assert.equal(s.director.select(s.input()),null);const q=s.input();q.geometry.objectHeights=[{id:'unknown',z:0}];s.director.observe(q);assert.equal(s.director.select(q).objective.motivation,'COLLECT_RESOURCE');});
