/* Source-extracted tests for the actual additive engine methods. No replacement Game implementation is asserted. */
'use strict';const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),os=require('node:os');
const R=process.env.HORIZON_REPO||path.resolve(__dirname,'../..');
const ts=require(fs.existsSync(R+'/node_modules/typescript')?R+'/node_modules/typescript':path.join(cp.execFileSync(process.platform==='win32'?'npm.cmd':'npm',['root','-g'],{encoding:'utf8',shell:process.platform==='win32'}).trim(),'typescript'));
const s=fs.readFileSync(R+'/src/game/agentEnvironment.ts','utf8'),sf=ts.createSourceFile('agentEnvironment.ts',s,ts.ScriptTarget.Latest,true),cls=sf.statements.find(n=>ts.isClassDeclaration(n)&&n.name?.text==='AgentEnvironment');
const methods=['inspectHorizonIntent','setHorizonGhostView','getHorizonGhostView'].map(name=>{const matches=cls.members.filter(m=>m.name?.getText(sf)===name);assert.equal(matches.length,1);return matches[0].getText(sf);}).join('\n');
const header=`const AGENT_SIMULATION_MODE=false;const RoomType={BOSS:'boss'};const Direction={UP:1,RIGHT:2,DOWN:0,LEFT:3};class Harness{busy=false;failure:string|null=null;game:any;constructor(game:any){this.game=game;}player():{getRoom:()=>{globalId:string;depth:number;pathId:string;type:string;entities:{isEnemy:boolean;dead:boolean}[];items:{id?:string;globalId:string;pickedUp:boolean;z:number}[];roomArray:Record<number,Record<number,any>>};z:number;dead:boolean;inventory:{isOpen:boolean};screenMessage:{open:boolean};menu?:{open:boolean}}{return this.game.player;}inspectHorizonRoom():{schemaVersion:number;roomId:string;tiles:{x:number;y:number;z:number}[]}{return this.game.geometry;}\n`;
const mod={exports:{}};new Function('module','exports',ts.transpileModule(header+methods+'\n};exports.Harness=Harness;', {compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.CommonJS}}).outputText)(mod,mod.exports);
function fake(){const target={globalId:'B',depth:0,entered:false},tile={linkedDoor:{room:target},getAgentHazardTraits:()=>({kind:'spikes',active:false})},room={globalId:'A',depth:0,pathId:'main',type:'boss',entities:[{isEnemy:true,dead:false}],items:[],roomArray:{1:{1:tile}}},game={player:{getRoom:()=>room,z:0,dead:false,inventory:{isOpen:false},screenMessage:{open:false},menu:{open:false}},geometry:{schemaVersion:1,roomId:'A',tiles:[{x:1,y:1,z:0}]},constructor:{playerset:{id:'sheet'}}};return{h:new mod.exports.Harness(game),game,target};}
test('intent method discloses only entered directed destinations and no future-room contents',()=>{const f=fake(),a=f.h.inspectHorizonIntent();assert.equal(a.tiles[0].destination,null);f.target.entered=true;const b=f.h.inspectHorizonIntent();assert.deepEqual(b.tiles[0].destination,{roomId:'B',depth:0});assert.equal(b.room.progressBlockedByEnemies,true);assert.equal(b.coverage,'full-current-room');assert.ok(!('entities' in b.tiles[0].destination));});
test('intent inspection does not mutate geometry and refuses active operations',()=>{const f=fake(),before=JSON.stringify(f.game);f.h.inspectHorizonIntent();assert.equal(JSON.stringify(f.game),before);f.h.busy=true;assert.throws(()=>f.h.inspectHorizonIntent(),/idle/);});
test('presentation view is opt-in, detached and hides modal/unfinished gameplay',()=>{const f=fake();assert.equal(f.h.getHorizonGhostView(),null);f.h.setHorizonGhostView(true);f.game.horizonGhostViewFrame={matrix:[1,0,0,1,10,20],capturedAt:performance.now(),roomId:'A',depth:0,tileSize:16};let x=f.h.getHorizonGhostView();assert.equal(x.hidden,false);x.matrix[0]=999;assert.equal(f.game.horizonGhostViewFrame.matrix[0],1);f.game.player.inventory.isOpen=true;assert.equal(f.h.getHorizonGhostView().hidden,true);f.h.setHorizonGhostView(false);assert.equal(f.h.getHorizonGhostView(),null);});
test('new TypeScript methods pass strict isolated source typecheck',()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'expedition-types-'));try{const file=path.join(d,'harness.ts');fs.writeFileSync(file,header+methods+'\n}');const config=path.join(d,'tsconfig.json');fs.writeFileSync(config,JSON.stringify({compilerOptions:{strict:true,target:'ES2020',lib:['ES2020','DOM'],types:[],skipLibCheck:true,noEmit:true},files:[file]}));const local=fs.existsSync(R+'/node_modules/typescript/bin/tsc')?R+'/node_modules/typescript/bin/tsc':path.join(cp.execFileSync(process.platform==='win32'?'npm.cmd':'npm',['root','-g'],{encoding:'utf8',shell:process.platform==='win32'}).trim(),'typescript/bin/tsc');const result=cp.spawnSync(process.execPath,[local,'-p',config],{encoding:'utf8'});assert.equal(result.status,0,result.stdout+result.stderr);}finally{fs.rmSync(d,{recursive:true,force:true});}});
