'use strict';const test=require('node:test'),assert=require('node:assert/strict');const R=process.env.HORIZON_REPO||require('node:path').resolve(__dirname,'../..');const G=require(R+'/agent-horizon-ghosts.js'),D=require(R+'/agent-horizon-driver.js');
const edge={type:'edge',atMs:0,nodeId:1,parentId:0,from:{roomId:'A',depth:0,x:1,y:1,z:0},to:{roomId:'A',depth:0,x:2,y:1,z:0},action:{type:'Move',direction:'right'},outcome:'safe',healthLoss:0};
test('ghost pose is fixed without idle phase and interpolates actual movement only',()=>{const p=G.pose(edge,80);assert.equal(p.x,1.5);assert.equal(p.direction,'right');assert.ok(!('frame' in p));assert.equal(G.pose(edge,-1),null);assert.equal(G.pose(edge,2000),null);});
test('damage branch flashes red then fades and never represents a real death',()=>{const e={...edge,outcome:'damage-pruned',healthLoss:1};assert.equal(G.pose(e,170).hurt,true);assert.ok(G.pose(e,170).alpha>G.pose(e,400).alpha);assert.equal(G.pose(e,1000),null);assert.equal(G.pose(e,170).rejected,false);});
test('unknown or rejected branch is not displayed as hurt/death',()=>{const p=G.pose({...edge,to:null,outcome:'error'},200);assert.equal(p.rejected,true);assert.equal(p.hurt,false);assert.equal(p.x,1);});
test('room transition has no invented connecting segment across unrelated coordinates',()=>{const p=G.pose({...edge,to:{roomId:'B',depth:0,x:40,y:20,z:0}},80);assert.equal(p.exit,true);assert.equal(p.x,1);assert.equal(p.to.roomId,'A');});
function canvas(){const calls=[];const ctx=new Proxy({calls},{get(t,k){if(k in t)return t[k];return (...args)=>calls.push([k,...args]);},set(t,k,v){t[k]=v;return true;}});return{width:400,height:300,getContext:()=>ctx,ctx,calls};}
test('drawing preserves canvas state and never calls an engine renderer or action',()=>{const tr=D.createTrace();tr.begin(edge.from,{});tr.emit({...edge,atMs:0});const c=canvas(),v={roomId:'A',depth:0,z:0,ageMs:0,matrix:[2,0,0,2,10,20],tileSize:16,hidden:false};let count=0;const r=G.create({trace:tr,getView:()=>v,canvas:c,drawSprite:(_,p)=>{count++;assert.ok(p.alpha>0);}});r.draw();r.seek(80);assert.ok(count>0);assert.ok(c.calls.some(x=>x[0]==='setTransform'&&x[1]===2));assert.equal(c.ctx.globalAlpha,1);r.dispose();});
test('ghosts are clipped by room, floor and z, not only coordinates',()=>{const tr=D.createTrace();tr.begin(edge.from,{});tr.emit({...edge,atMs:0});const c=canvas(),v={roomId:'B',depth:0,z:0,ageMs:0,matrix:[1,0,0,1,0,0],tileSize:16};let draws=0;const r=G.create({trace:tr,getView:()=>v,canvas:c,drawSprite:()=>draws++});r.draw();r.seek(80);assert.equal(draws,0);v.roomId='A';v.depth=1;r.seek(80);assert.equal(draws,0);v.depth=0;v.z=1;r.seek(80);assert.equal(draws,0);r.dispose();});
test('ghost display cap and trace overflow are reported without changing the search',()=>{const tr=D.createTrace();tr.begin(edge.from,{});for(let i=0;i<8;i++)tr.emit({...edge,nodeId:i+1,atMs:0});const r=G.create({trace:tr,getView:()=>({roomId:'A',depth:0,z:0,ageMs:0,matrix:[1,0,0,1,0,0],tileSize:16}),canvas:canvas(),maxGhosts:2,drawSprite:()=>{}});r.draw();r.seek(80);assert.equal(r.stats().rendered,2);assert.equal(r.stats().retainedEdges,8);r.dispose();});
test('new query replaces old ghost trace, and stale camera view draws nothing',()=>{const tr=D.createTrace();tr.begin(edge.from,{});tr.emit({...edge,atMs:0});let age=0;const r=G.create({trace:tr,getView:()=>({roomId:'A',depth:0,z:0,ageMs:age,matrix:[1,0,0,1,0,0],tileSize:16}),canvas:canvas(),drawSprite:()=>{}});r.draw();r.seek(80);assert.equal(r.stats().retainedEdges,1);tr.begin(edge.from,{});r.draw();assert.equal(r.stats().retainedEdges,0);tr.emit({...edge,atMs:0});age=1000;r.seek(80);assert.equal(r.stats().rendered,0);r.dispose();});
test('mutable event inputs and consumer copies cannot rewrite the source trace',()=>{const tr=D.createTrace(),data=JSON.parse(JSON.stringify(edge));tr.begin(edge.from,{});tr.emit(data);data.from.x=999;const out=tr.snapshot();out.events[1].from.x=998;assert.equal(tr.snapshot().events[1].from.x,1);});
test('disabling the engine projection clears a stale ghost overlay',()=>{const tr=D.createTrace(),c=canvas();let v={roomId:'A',depth:0,z:0,ageMs:0,matrix:[1,0,0,1,0,0],tileSize:16};tr.begin(edge.from,{});tr.emit({...edge,atMs:0});const r=G.create({trace:tr,getView:()=>v,canvas:c,drawSprite:()=>{}});r.draw();r.seek(80);assert.equal(r.stats().rendered,1);v=null;r.draw();assert.equal(r.stats().rendered,0);assert.equal(c.calls.at(-1)[0],'clearRect');r.dispose();});
